openapi: 3.0.3
info:
  title: Users API
  description: Users API
  version: 1.0.0
paths:
  /users:
    get:
      tags: [Users]
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags: [Users]
      requestBody:
        description: User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      tags: [Users]
      parameters:
        - name: id
          in: path
          schema:
            type: integer
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string

