// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, name string) (User, error)
	FindUserByID(ctx context.Context, db DBTX, id int64) (User, error)
	FindUsers(ctx context.Context, db DBTX) ([]User, error)
}

var _ Querier = (*Queries)(nil)
